spring.application.name=demo

spring.datasource.url=jdbc:mysql://59.145.65.84:2001/research_register
spring.datasource.username=researchuser
spring.datasource.password=kishor
spring.jpa.hibernate.ddl-auto = update
server.servlet.context-path = /api/v1.0
server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false



aws.access.key=AKIAYCOZSYX3KR3AKN7N
aws.secret.key=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
aws.region=ap-southeast-2
aws.bucket.name=billing-software-ajaym

jwt.secret.key=MySuperSecureJwtSecretKeyThatIsAtLeast32Chars!!
