server.port=9097
server.address=0.0.0.0
spring.application.name=demo

spring.datasource.url=jdbc:mysql://49.249.61.246:3307/research_register
spring.datasource.username=research_user
spring.datasource.password=research@2024

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.servlet.session.cookie.same-site=None
server.servlet.session.cookie.secure=false

aws.access.key=dummy
aws.secret.key=dummy
aws.region=ap-southeast-2
aws.bucket.name=dummy-bucket