spring.application.name=demo


aws.access.key=AKIAREVC3BEIGUSTR6XG
aws.secret.key=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
aws.region=ap-south-1
aws.bucket.name=billing-software-teja

jwt.secret.key=thisismysecretkeyforthisupcomingproject